#
# pre-commit check-branch configuration
# <https://github.com/commit-check/commit-check>
#
[branch]
# See <https://github.com/pdfclown/pdfclown-common/blob/main/docs/common/maintenance.md#branches>
# for more information.
conventional_branch = true
allow_branch_types = [
    "build", "bump",
    "chore", "ci",
    "dependabot", "docs",
    "feat", "fix",
    "perf",
    "r", "refactor", "release", "revert",
    "style",
    "test"
    ]
